[package]
name = "matrix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Renderer
rand = "0.8.5"
structopt = "0.3.25"
# Qt
qmetaobject = "0.2"
cstr = "0.2"
